// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qckglvqwauqoamtvnosn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFja2dsdnF3YXVxb2FtdHZub3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTEyNjgsImV4cCI6MjA3MzgyNzI2OH0.g1L7-5EO9g5JnVuh3Hx7t2TURMq2l0zVX9jR-l7lLnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});